---
abstract: 'XS for C++'
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
build_requires:
  Test::Base: 0
  Test::Differences: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-XSpp
provides:
  ExtUtils::XSpp:
    file: lib/ExtUtils/XSpp.pm
    version: 0.08
  ExtUtils::XSpp::Cmd:
    file: lib/ExtUtils/XSpp/Cmd.pm
  ExtUtils::XSpp::Driver:
    file: lib/ExtUtils/XSpp/Driver.pm
  ExtUtils::XSpp::Grammar:
    file: lib/ExtUtils/XSpp/Grammar.pm
  ExtUtils::XSpp::Grammar::YappDriver:
    file: lib/ExtUtils/XSpp/Grammar.pm
    version: 1.05
  ExtUtils::XSpp::Node:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Access:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Argument:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Class:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Comment:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Constructor:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Destructor:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::File:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Function:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Method:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Module:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Package:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Raw:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Node::Type:
    file: lib/ExtUtils/XSpp/Node.pm
  ExtUtils::XSpp::Parser:
    file: lib/ExtUtils/XSpp/Parser.pm
  ExtUtils::XSpp::Typemap:
    file: lib/ExtUtils/XSpp/Typemap.pm
  ExtUtils::XSpp::Typemap::parsed:
    file: lib/ExtUtils/XSpp/Typemap.pm
  ExtUtils::XSpp::Typemap::reference:
    file: lib/ExtUtils/XSpp/Typemap.pm
  ExtUtils::XSpp::Typemap::simple:
    file: lib/ExtUtils/XSpp/Typemap.pm
requires:
  ExtUtils::ParseXS: 2.22
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
